// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_shaders.py
// Compiled with D3DCOMPILE_OPTIMIZATION_LEVEL3

#pragma once

#include "overlay_shader_bytecode/vs_4_0.h"
#include "overlay_shader_bytecode/vs_5_0.h"
#include "overlay_shader_bytecode/ps_textured_4_0.h"
#include "overlay_shader_bytecode/ps_textured_5_0.h"
#include "overlay_shader_bytecode/ps_textured_sdr_5_0.h"
#include "overlay_shader_bytecode/ps_solid_4_0.h"
#include "overlay_shader_bytecode/ps_solid_5_0.h"
#include "overlay_shader_bytecode/ps_textured_descfree_5_0.h"
