// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once

#include "sharpen_shader_bytecode/sharpenvs_5_0.h"
#include "sharpen_shader_bytecode/sharpenps_cas_5_0.h"
#include "sharpen_shader_bytecode/sharpenps_rcas_5_0.h"
