// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once

#include "sharpen_shader_spirv/sharpenvertexshaderspv.h"
#include "sharpen_shader_spirv/sharpencasfragmentshaderspv.h"
#include "sharpen_shader_spirv/sharpenrcasfragmentshaderspv.h"
