#pragma once

#include "media_main_internal.h"

// Session state for the encoder thread (formerly the single EncoderThreadFunc body in
// media_main_threads.cpp). Locals became members, lambdas became private methods, and the
// monolithic loop became phase methods so each unit is a readable semantic chunk under the
// 800-line ceiling.

class MediaEncoderSession {
public:
    explicit MediaEncoderSession(const AppConfig& config) : config(config) {}
    void Run();

private:
    const AppConfig& config;

    // Active tryPopBufferedWgcFrameForTarget call parameters (the decomposed selection
    // helpers read these instead of taking the original lambda parameters).
    int64_t selectionTargetQpc = 0;
    int64_t liveSelectionTargetQpc = 0;
    int64_t liveNowQpc = 0;
    bool selectionDelayApplied = false;
    QueuedFrame* selectedFrame = nullptr;
    bool* repeatedBecauseNoFrameCoverage = nullptr;
    // Phase methods that moved out of the encoder loop body signal a loop jump back to Run().
    bool continueMainLoop = false;
    bool breakMainLoop = false;

    struct WgcStarvedEpisodeSummary {
            bool active = false;
            uint64_t startTickMs = 0;
            int64_t startQpc = 0;
            uint64_t startLiveTicks = 0;
            uint64_t startDuplicateTicks = 0;
            uint32_t minInputFps = std::numeric_limits<uint32_t>::max();
            uint32_t minDeliveredFps = std::numeric_limits<uint32_t>::max();
            uint32_t peakFreshMissPermille = 0;
            uint32_t minBufferedFrames = std::numeric_limits<uint32_t>::max();
            uint32_t maxCallbackGapUs = 0;
            uint32_t maxCopyUs = 0;
            uint32_t maxFenceUs = 0;
            uint32_t maxMuxBackpressureCount = 0;
            uint32_t maxMuxBackpressureWaitUs = 0;
            uint32_t maxMuxQueueKb = 0;
            uint32_t peakOverloadFlags = 0;
            uint32_t startPoolSaturatedDrops = 0;
            uint32_t startPoolOverwritePrevented = 0;
            uint32_t startIngressDecimated = 0;
            double maxEncodeEmaMs = 0.0;
        
            void Reset() {
                *this = {};
                minInputFps = std::numeric_limits<uint32_t>::max();
                minDeliveredFps = std::numeric_limits<uint32_t>::max();
                minBufferedFrames = std::numeric_limits<uint32_t>::max();
            }
    };

    struct CaptureSessionSummary {
            uint64_t duplicateTicks = 0;
            uint64_t duplicateNoSourceTicks = 0;
            uint64_t duplicateDeferredTicks = 0;
            uint64_t duplicateTimerTicks = 0;
            uint64_t duplicateDrainTicks = 0;
            uint64_t queueTickSamples = 0;
            uint64_t noFreshTicks = 0;
            uint64_t noReserveTicks = 0;
            uint64_t starvedEpisodes = 0;
            uint64_t longestStarvedEpisodeMs = 0;
            uint64_t longestStarvedEpisodeOutputTicks = 0;
            uint64_t longestStarvedEpisodeDuplicateTicks = 0;
            // Longest CONTIGUOUS duplicate (held-frame) run for the whole session -- the true visible
            // freeze duration. Unlike the per-window cadence DupStreak, this survives the per-second
            // cadence reset, so a freeze that crosses a window boundary is not split/undercounted.
            // (longestStarvedEpisode* above measure a below-target *episode* and dups *within* it, which
            // overstate a freeze because the source still delivers new frames during the episode.)
            uint64_t longestContiguousDupTicks = 0;
            uint32_t currentContiguousDupTicks = 0;  // running counter (per-tick), reset on any fresh frame
            uint32_t longestStarvedEpisodeMinInputFps = std::numeric_limits<uint32_t>::max();
            uint32_t longestStarvedEpisodeMinDeliveredFps = std::numeric_limits<uint32_t>::max();
            uint32_t worstFreshMissPermille = 0;
            uint32_t worstSourceFpsX100 = std::numeric_limits<uint32_t>::max();
            uint32_t bestSourceFpsX100 = 0;
            uint32_t worstInputMin250Fps = std::numeric_limits<uint32_t>::max();
            uint32_t worstDeliveredMin250Fps = std::numeric_limits<uint32_t>::max();
            uint32_t worstSourceJitterUs = 0;
            uint32_t worstSelectionErrorUs = 0;
            uint32_t worstWgcSelectionErrorUs = 0;
            uint32_t worstOldestBufferedFrameAgeUs = 0;
            uint32_t worstOneSecondEmitCount = 0;
            uint32_t worstOneSecondUniqueCount = 0;
            uint32_t worstOneSecondRepeatCount = 0;
            uint32_t lowSourceImmediateExits = 0;
            double maxShortfallDurationMs = 0.0;
            double maxEncodeEmaMs = 0.0;
            double minEncoderSustainFps = std::numeric_limits<double>::max();
            uint32_t maxWgcContentPhaseErrorUs = 0;
        
            void Reset() {
                *this = {};
                longestStarvedEpisodeMinInputFps = std::numeric_limits<uint32_t>::max();
                longestStarvedEpisodeMinDeliveredFps = std::numeric_limits<uint32_t>::max();
                worstSourceFpsX100 = std::numeric_limits<uint32_t>::max();
                worstInputMin250Fps = std::numeric_limits<uint32_t>::max();
                worstDeliveredMin250Fps = std::numeric_limits<uint32_t>::max();
                minEncoderSustainFps = std::numeric_limits<double>::max();
            }
    };

    struct ScreenGrabPrivacyContext {
            HWND targetWindow = nullptr;
            HMONITOR targetMonitor = nullptr;
            bool stableCaptureTarget = false;
            ce::screen_grab_privacy::FullscreenFocusSnapshot focus;
    };

    LARGE_INTEGER qpcFreq{};
    ce::screen_grab_privacy::ScreenGrabPrivacyRuntime privacyRuntime{};
    int64_t targetIntervalTicks;
    uint32_t captureSyncMultiplier;
    bool captureSyncPhaseLockEnabled;
    int64_t captureSyncSourceIntervalTicks;
    LARGE_INTEGER nextSampleTime{};
    HANDLE hTimer;
    double smoothedEncodeMs;
    ce::capture_policy::RecordingHealthState recordingHealthState{};
    double smoothedWgcFreshServiceMs;
    double smoothedWgcRepeatServiceMs;
    uint32_t wgcFreshServiceSamples;
    uint32_t wgcRepeatServiceSamples;
    ce::capture_policy::WgcOverloadRepeatPacerState wgcOverloadRepeatPacer{};
    double frameIntervalMs;
    uint64_t encoderWakeLateAccumUs;
    uint64_t encoderWakeLateSamples;
    uint32_t encoderWakeLateMaxUs;
    std::vector<QueuedFrame> drainedScreenGrabFrames{};
    std::vector<WGCCapturedFrame> drainedWgcCapturedFrames{};
    std::deque<QueuedFrame> bufferedWgcFrames{};
    uint64_t observedWgcSourceEpoch;
    bool lastSuccessfulWgcCursorEmbedded;
    bool hasSuccessfulWgcCursorMetadata;
    std::vector<size_t> wgcFreshCandidateIndices{};
    std::vector<size_t> wgcFallbackCandidateIndices{};
    std::vector<size_t> wgcRelaxedFreshCandidateIndices{};
    std::vector<size_t> wgcRelaxedFallbackCandidateIndices{};
    std::vector<size_t> wgcRepeatRescueCandidateIndices{};
    std::vector<QueuedFrame> drainedInjectFrames{};
    std::deque<QueuedFrame> bufferedInjectFrames{};
    double smoothedInjectFenceMs;
    bool recordingOutputLive;
    bool pendingLiveActivation;
    uint64_t startupWarmupStartTick;
    uint64_t recordingLiveTick;
    uint32_t hiddenStartupFrames;
    ce::capture_policy::WarmupTransitionState warmupState;
    uint32_t pendingInjectTrimmedLogCount;
    size_t maxBufferedInjectDepthSinceLog;
    DWORD lastInjectTrimLog;
    uint32_t pacingInputThisWindow;
    uint32_t pacingTicksThisWindow;
    uint32_t pacingEmaUpdates;
    double smoothedInputPerTick;
    double frameCreditAccumulator;
    int64_t encoderGridStartQpc;
    int64_t encoderGridTickCount;
    uint64_t selectionLogCounter;
    uint32_t lastEncodedInjectFrameIndex;
    std::array<uint32_t, media_main_kInjectTextureSlotCount> lastEncodedFrameByTextureIndex{};
    InjectFrameLineage lastDeferredLineage{};
    InjectFrameLineage lastSuccessfullyEncodedInjectLineage{};
    CadenceHealthCounters cadenceCounters{};
    InputFrameRatePredictor wgcInputPredictor{};
    InputFrameRatePredictor injectInputPredictor{};
    ce::capture_policy::CfrCadencePhaseLockState injectCfrPhaseLock{};
    ce::capture_policy::CfrCadencePhaseLockState wgcCfrPhaseLock{};
    struct InjectDisplayTimingObservation {
        uint64_t publicationWatermark = 0;
        uint32_t generation = 0;
        int64_t virtualTimestampQpc = 0;
        uint32_t ringIndex = 0;
        uint32_t frameIndex = 0;
    };
    std::deque<InjectDisplayTimingObservation> injectDisplayTimingObservations{};
    uint32_t injectDisplayTimingActiveGeneration;
    uint64_t injectDisplayTimingLastMatchedSequence;
    bool injectDisplayTimingOffsetValid;
    int64_t injectDisplayTimingOffsetQpc;
    uint64_t injectDisplayTimingResolvedCount;
    uint64_t injectDisplayTimingFallbackCount;
    uint64_t injectDisplayTimingPendingCount;
    DWORD injectDisplayTimingLastLog;
    uint32_t injectWorstSourceFpsX100;
    uint32_t injectBestSourceFpsX100;
    uint32_t injectWorstSourceJitterUs;
    uint32_t injectWorstSelectionErrorUs;
    double smoothedEncCycleMs;
    double smoothedInjectServiceMs;
    uint32_t injectServiceMaxUs;
    uint32_t encCycleMaxMs;
    uint32_t encodeSpikeCountThisSecond;
    uint32_t dupTimestampCount;
    uint32_t lastWgcDuplicateTimestampSkipCountForCadence;
    uint32_t lastDuplicateReasonNoSource;
    uint32_t lastDuplicateReasonDeferred;
    uint32_t lastDuplicateReasonTimerRebase;
    uint32_t lastDuplicateReasonDrain;
    uint32_t lastInvalidMetaCount;
    uint32_t lastInvalidHandleCount;
    uint32_t lastTimestampRegressionCount;
    uint32_t lastTimestampStallCount;
    uint32_t lastPacketClampCount;
    uint32_t lastNegativePtsCount;
    uint32_t lastNonMonotonicPtsCount;
    uint32_t injectDeferredRequeuedThisWindow;
    uint32_t injectDeferredDroppedThisWindow;
    uint64_t injectDeferredRequeuedTotal;
    uint64_t injectDeferredDroppedTotal;
    uint32_t injectFreshCatchupThisWindow;
    uint32_t injectRepeatCatchupThisWindow;
    uint32_t injectLiveStaleTrimThisWindow;
    uint32_t injectTargetSelectThisWindow;
    uint32_t injectTargetSupersededThisWindow;
    uint32_t injectTargetHoldThisWindow;
    uint32_t injectTargetHoldWithCandidateThisWindow;
    uint32_t activePathMismatchDiscardThisWindow;
    uint64_t injectFreshCatchupTotal;
    uint64_t injectRepeatCatchupTotal;
    uint64_t injectLiveStaleTrimTotal;
    uint64_t injectTargetSelectTotal;
    uint64_t injectTargetSupersededTotal;
    uint64_t injectTargetHoldTotal;
    uint64_t injectTargetHoldWithCandidateTotal;
    uint64_t injectBufferCapTrimTotal;
    uint32_t injectTargetResidualMaxUs;
    bool injectCfrRecoveryActive;
    bool injectEncoderServiceTooSlowCurrent;
    uint32_t injectCfrRecoveryEpisodesThisWindow;
    uint64_t injectCfrRecoveryEpisodesTotal;
    uint64_t injectCfrRecoveryStartTick;
    uint32_t injectCfrRecoveryStartDebt;
    uint32_t injectCfrRecoveryBestDebt;
    uint64_t injectCfrRecoveryStartFreshCatchup;
    uint64_t injectCfrRecoveryStartRepeatCatchup;
    uint64_t injectCfrRecoveryLastProgressLogTick;
    uint64_t activePathMismatchDiscardTotal;
    size_t pendingLiveInjectReadyFrames;
    DWORD lastHealthLog;
    LARGE_INTEGER liveStartQpc{};
    uint64_t liveTicksOutput;
    uint64_t liveTicksScheduled;
    uint64_t liveTicksDiscardedByTimerRebase;
    uint64_t wgcVisualDebtMaxExcessTicks;
    uint64_t wgcLiveSchedulerRebaseTotal;
    uint32_t wgcLiveSchedulerRebaseMaxTicks;
    uint32_t wgcLiveSchedulerRebaseThisWindow;
    bool wgcStopDrainHeldFrameLogged;
    uint64_t wgcSelectionErrorAccumUs;
    int64_t wgcSelectionErrorSignedAccumUs;
    uint32_t wgcSelectionErrorSamples;
    uint32_t wgcSelectionErrorMaxUs;
    uint32_t wgcSelectionEarlyMaxUs;
    uint32_t wgcSelectionLateMaxUs;
    uint32_t wgcSelectionTargetClampCount;
    uint32_t wgcSelectionTargetClampMaxUs;
    uint32_t wgcHoldForNextTickCount;
    uint32_t wgcSelectionDelayTickCount;
    uint32_t wgcSyncDelayHoldCount;
    uint64_t wgcSyncDelayHoldTotal;
    uint32_t wgcSyncDelaySourceLimitedHoldCount;
    uint64_t wgcSyncDelaySourceLimitedHoldTotal;
    uint32_t wgcSyncDelayPolicyHoldCount;
    uint64_t wgcSyncDelayPolicyHoldTotal;
    uint32_t wgcTooNewLeadMaxUs;
    uint32_t wgcTooNewLeadSessionMaxUs;
    uint32_t wgcStartupReserveFrames;
    int64_t wgcStartupReserveSpanUs;
    int64_t wgcStartupDelayTargetUs;
    bool wgcStartupSelectedByDelayReserve;
    std::string wgcStartupReserveReason;
    int64_t wgcSmoothnessActiveDelayQpc;
    ce::capture_policy::CfrTimelineStartContract pendingWgcStartContract{};
    uint64_t pendingWgcStartContractGeneration;
    uint64_t committedWgcStartContractGeneration;
    bool wgcEncoderPrewarmAttempted;
    bool wgcEncoderPrewarmSucceeded;
    int64_t wgcEncoderPrewarmElapsedUs;
    int64_t wgcSmoothnessFloorDelayQpc;
    int64_t wgcSmoothnessFloorRequestedQpc;
    const char* wgcSmoothnessFloorSource;
    const char* wgcSmoothnessFloorClampedBy;
    bool wgcSmoothnessFloorLogged;
    ce::capture_policy::WgcSmoothnessFloorJitter wgcSmoothnessFloorJitter{};
    uint32_t wgcSmoothnessDesiredFrames;
    uint32_t wgcSmoothnessRetainedFrames;
    uint32_t wgcSmoothnessActualFrames;
    uint32_t wgcSmoothnessPoolSlots;
    uint32_t wgcSmoothnessRetainedFrameCap;
    uint32_t wgcSmoothnessReservedFreeSlots;
    uint64_t wgcSmoothnessEstimatedVramBytes;
    bool wgcSmoothnessCapLimited;
    std::string wgcSmoothnessBufferReason;
    uint32_t wgcDelayReservoirLowWaterTickCount;
    uint64_t wgcDelayReservoirLowWaterTickTotal;
    uint64_t wgcTsSmoothSamplesWindow;
    uint64_t wgcTsSmoothDevAccumUsWindow;
    uint32_t wgcTsSmoothDevMaxUsWindow;
    uint32_t wgcTsSmoothDevMaxUsTotal;
    uint32_t wgcTsSmoothSnapCountWindow;
    uint64_t wgcTsSmoothSnapCountTotal;
    uint64_t wgcDelayResidualSamples;
    uint64_t wgcDelayResidualAbsAccumUs;
    int64_t wgcDelayResidualSignedAccumUs;
    uint32_t wgcDelayResidualAbsMaxUs;
    uint32_t wgcDelayResidualLateMaxUs;
    uint32_t wgcDelayResidualEarlyMaxUs;
    uint64_t wgcDelayRealizedAccumUs;
    uint32_t wgcDelayRealizedMinUs;
    uint32_t wgcDelayRealizedMaxUs;
    std::array<uint32_t, 256> wgcDelayResidualAbsHistogram{};
    uint64_t wgcDelayResidualWindowSamples;
    uint64_t wgcDelayResidualWindowAbsAccumUs;
    int64_t wgcDelayResidualWindowSignedAccumUs;
    uint32_t wgcDelayResidualWindowAbsMaxUs;
    uint32_t wgcDelayResidualWindowLateMaxUs;
    std::array<uint32_t, 256> wgcDelayResidualWindowAbsHistogram{};
    uint64_t wgcDelayRawResidualSamples;
    uint64_t wgcDelayRawResidualAbsAccumUs;
    int64_t wgcDelayRawResidualSignedAccumUs;
    uint32_t wgcDelayRawResidualAbsMaxUs;
    uint32_t wgcDelayRawResidualLateMaxUs;
    uint32_t wgcDelayRawResidualEarlyMaxUs;
    std::array<uint32_t, 256> wgcDelayRawResidualAbsHistogram{};
    uint64_t wgcDelayRawResidualWindowSamples;
    uint64_t wgcDelayRawResidualWindowAbsAccumUs;
    int64_t wgcDelayRawResidualWindowSignedAccumUs;
    uint32_t wgcDelayRawResidualWindowAbsMaxUs;
    uint32_t wgcDelayRawResidualWindowLateMaxUs;
    std::array<uint32_t, 256> wgcDelayRawResidualWindowAbsHistogram{};
    uint64_t wgcDelayRawMinusPredictedSamples;
    int64_t wgcDelayRawMinusPredictedSignedAccumUs;
    uint32_t wgcDelayRawMinusPredictedAbsMaxUs;
    uint64_t wgcDelayRawMinusPredictedWindowSamples;
    int64_t wgcDelayRawMinusPredictedWindowSignedAccumUs;
    uint32_t wgcDelayRawMinusPredictedWindowAbsMaxUs;
    uint64_t wgcDelayRelaxedSelectionCount;
    uint32_t wgcDelayRelaxedSelectionWindowCount;
    uint32_t wgcDelayRelaxedSelectionMaxUs;
    uint64_t wgcDelayRelaxedBetterTargetTotal;
    uint32_t wgcDelayRelaxedBetterTargetWindow;
    uint64_t wgcDelayRelaxedRepeatClusterTotal;
    uint32_t wgcDelayRelaxedRepeatClusterWindow;
    uint64_t wgcDelayRelaxedRejectedSyncRiskTotal;
    uint32_t wgcDelayRelaxedRejectedSyncRiskWindow;
    uint64_t wgcDelayRelaxedRejectedResidualHeadroomTotal;
    uint32_t wgcDelayRelaxedRejectedResidualHeadroomWindow;
    uint64_t wgcDelayRelaxedRejectedRepeatCostTotal;
    uint32_t wgcDelayRelaxedRejectedRepeatCostWindow;
    uint64_t wgcDelaySoftLateRejectedTotal;
    uint32_t wgcDelaySoftLateRejectedWindow;
    uint64_t wgcDelaySoftLateAcceptedTotal;
    uint32_t wgcDelaySoftLateAcceptedWindow;
    uint64_t wgcDelayNearCapAcceptedTotal;
    uint32_t wgcDelayNearCapAcceptedWindow;
    uint64_t wgcDelayUniformCadenceTotal;
    uint32_t wgcDelayUniformCadenceWindow;
    uint64_t wgcDelayUniformHoldTotal;
    uint32_t wgcDelayUniformHoldWindow;
    uint64_t wgcDelayPaceCapTrimTotal;
    uint32_t wgcDelayPaceCapTrimWindow;
    DWORD wgcDelayPaceCapTrimLastLogTick;
    uint64_t wgcUniformGridDebtHoldTotal;
    uint64_t wgcUniformGridDebtLeadMaxUs;
    uint64_t wgcRetainedCapTrimTotal;
    uint32_t wgcRetainedCapTrimWindow;
    DWORD wgcRetainedCapTrimLastLogTick;
    uint64_t wgcPoolPressureTrimTotal;
    uint32_t wgcPoolPressureTrimWindow;
    DWORD wgcPoolPressureTrimLastLogTick;
    uint64_t wgcDelayOlderFrameAvoidedRepeatTotal;
    uint32_t wgcDelayOlderFrameAvoidedRepeatWindow;
    uint64_t wgcDelaySourceLimitedRepeatTotal;
    uint32_t wgcDelaySourceLimitedRepeatWindow;
    uint64_t wgcDelayRepeatRescueAttemptTotal;
    uint32_t wgcDelayRepeatRescueAttemptWindow;
    uint64_t wgcDelayRepeatRescueSuccessTotal;
    uint32_t wgcDelayRepeatRescueSuccessWindow;
    uint64_t wgcDelayRepeatRescueRejectedSyncTotal;
    uint32_t wgcDelayRepeatRescueRejectedSyncWindow;
    uint64_t wgcDelayRepeatRescueRejectedHeadroomTotal;
    uint32_t wgcDelayRepeatRescueRejectedHeadroomWindow;
    uint64_t wgcDelayRepeatRescueRejectedCostTotal;
    uint32_t wgcDelayRepeatRescueRejectedCostWindow;
    uint64_t wgcDelayRepeatPromotedBeforeRepeatTotal;
    uint32_t wgcDelayRepeatPromotedBeforeRepeatWindow;
    uint64_t wgcDelayRepeatPromotionAttemptTotal;
    uint32_t wgcDelayRepeatPromotionAttemptWindow;
    uint64_t wgcDelayRepeatPromotionRejectedSoftTotal;
    uint32_t wgcDelayRepeatPromotionRejectedSoftWindow;
    uint64_t wgcDelayRepeatSafeAfterPromotionTotal;
    uint32_t wgcDelayRepeatSafeAfterPromotionWindow;
    uint64_t wgcDelayRepeatWithSafeCandidateTotal;
    uint32_t wgcDelayRepeatWithSafeCandidateWindow;
    uint64_t wgcDelayRepeatWithoutSafeCandidateTotal;
    uint32_t wgcDelayRepeatWithoutSafeCandidateWindow;
    uint64_t wgcDelayRepeatWithSoftSafeCandidateTotal;
    uint32_t wgcDelayRepeatWithSoftSafeCandidateWindow;
    uint64_t wgcDelayRepeatWithoutSoftSafeCandidateTotal;
    uint32_t wgcDelayRepeatWithoutSoftSafeCandidateWindow;
    uint64_t wgcDelayRepeatHardOnlyCandidateTotal;
    uint32_t wgcDelayRepeatHardOnlyCandidateWindow;
    uint64_t wgcDelaySyncProtectedRepeatTotal;
    uint32_t wgcDelaySyncProtectedRepeatWindow;
    uint64_t wgcDelayWindowHealthyRepeatTotal;
    uint32_t wgcDelayWindowHealthyRepeatWindow;
    uint64_t wgcDelayWindowRecoverableRepeatTotal;
    uint32_t wgcDelayWindowRecoverableRepeatWindow;
    uint64_t wgcDelayWindowSourceLimitedRepeatTotal;
    uint32_t wgcDelayWindowSourceLimitedRepeatWindow;
    uint64_t wgcDelayWindowHardStallRepeatTotal;
    uint32_t wgcDelayWindowHardStallRepeatWindow;
    uint64_t wgcDelayWindowPostStallRepeatTotal;
    uint32_t wgcDelayWindowPostStallRepeatWindow;
    uint64_t wgcDelayPostStallSafeFrameTotal;
    uint32_t wgcDelayPostStallSafeFrameWindow;
    uint32_t wgcDelayRepeatReserveDepthMax;
    uint32_t wgcDelayRepeatReserveDepthWindowMax;
    uint32_t wgcDelayRepeatReserveSpanMaxUs;
    uint32_t wgcDelayRepeatReserveSpanWindowMaxUs;
    uint32_t wgcDelayOldestSoftSafeAgeMaxUs;
    uint32_t wgcDelayOldestSoftSafeAgeWindowMaxUs;
    uint64_t wgcDelayPostSelectionRejectedSyncRiskTotal;
    uint32_t wgcDelayPostSelectionRejectedSyncRiskWindow;
    uint64_t wgcDelayPostSelectionRescuedSyncRiskTotal;
    uint32_t wgcDelayPostSelectionRescuedSyncRiskWindow;
    uint64_t wgcDelayRepeatClusterPressureTotal;
    uint32_t wgcDelayRepeatClusterPressureWindow;
    uint32_t wgcDelayRepeatClusterPressureWindowMaxTicks;
    uint32_t wgcDelayRepeatClusterPressureMaxTicks;
    uint64_t wgcSourceRepeatLowerBoundTotal;
    uint32_t wgcSourceRepeatLowerBoundWindow;
    static constexpr size_t kWgcRollingSourceWindowSlots = 5;
    std::array<uint32_t, kWgcRollingSourceWindowSlots> wgcRollingSourceAcceptedSlots{};
    std::array<uint32_t, kWgcRollingSourceWindowSlots> wgcRollingSourceCfrTickSlots{};
    size_t wgcRollingSourceSlotIndex;
    size_t wgcRollingSourceSlotCount;
    uint32_t wgcRollingSourceAcceptedSum;
    uint32_t wgcRollingSourceCfrTickSum;
    uint32_t wgcRollingSourceAcceptedWindow;
    uint32_t wgcRollingSourceCfrTicksWindow;
    uint32_t wgcRollingSourceDeficitFrames;
    uint32_t wgcRollingSourceSurplusFrames;
    uint64_t wgcRollingSourceAcceptedTotal;
    uint64_t wgcRollingSourceCfrTickTotal;
    uint32_t wgcRollingSourceLastIngressAccepted;
    bool wgcRollingSourceWindowPrimed;
    uint64_t wgcExcessRepeatTotal;
    uint32_t wgcExcessRepeatWindow;
    uint64_t wgcPolicyAddedRepeatTotal;
    uint32_t wgcPolicyAddedRepeatWindow;
    uint64_t wgcExcessRepeatClusterTotal;
    uint32_t wgcExcessRepeatClusterWindow;
    uint32_t wgcExcessRepeatClusterMaxTicks;
    uint32_t wgcExcessRepeatClusterWindowMaxTicks;
    uint64_t wgcSyncDelaySourceRecoveryHoldTotal;
    uint32_t wgcSyncDelaySourceRecoveryHoldCount;
    uint64_t wgcActiveDelaySourceRecoveryUntilTick;
    uint64_t wgcActiveDelaySourceRecoveryTicks;
    uint32_t wgcProducerRateRetuneCount;
    uint64_t wgcProducerRateRetuneTotal;
    uint32_t wgcRecentDeliveredFps;
    uint32_t wgcRecentDeliveredMin250Fps;
    uint32_t wgcRecentDeliveredMin500Fps;
    uint32_t wgcRecentInputMin250Fps;
    uint32_t wgcRecentInputMin500Fps;
    uint32_t wgcNoFreshTickCount;
    uint32_t wgcQueueTickSampleCount;
    uint32_t wgcNoFreshTickPermille;
    uint32_t wgcBufferedAtTickSum;
    uint32_t wgcBufferedAtTickMin;
    uint32_t wgcNoReserveTickCount;
    uint32_t wgcAncientSelectionCount;
    uint32_t wgcFreshSelectionMissCount;
    uint32_t wgcHeldFreshFrameTickCount;
    uint32_t cfrCatchupTicksExecuted;
    int64_t wgcWarmupUntilQpc;
    int64_t wgcBiasAccumQpc;
    uint32_t wgcBiasClampCount;
    uint32_t wgcReserveSpendTickCount;
    uint32_t wgcStaleUniqueFallbackCount;
    uint32_t wgcRepeatNoFreshCount;
    uint32_t wgcRepeatPolicyHoldCount;
    uint64_t wgcRepeatPolicyHoldTotal;
    uint32_t wgcRepeatTimerLateCount;
    uint32_t wgcRepeatCatchupCount;
    uint32_t wgcFreshCatchupCount;
    uint64_t wgcRepeatCatchupTotal;
    uint64_t wgcFreshCatchupTotal;
    uint32_t wgcSelectFreshCount;
    uint32_t wgcSelectDuplicateSourceCount;
    uint32_t wgcDropObsoleteCount;
    uint32_t wgcDropStaleDebtCount;
    uint64_t wgcDropStaleDebtTotal;
    uint32_t wgcDropStaleDebtMaxUs;
    uint32_t wgcEncoderLimitedSourceDropThisWindow;
    uint64_t wgcEncoderLimitedSourceDropTotal;
    uint32_t wgcEncoderLimitedSourceDropMaxTicks;
    uint64_t wgcEncoderLimitedCadenceEventCount;
    uint32_t wgcEncoderLimitedSuppressedByLowSourceThisWindow;
    uint64_t wgcEncoderLimitedSuppressedByLowSourceTotal;
    uint32_t wgcCapacityPressureModeMismatchThisWindow;
    uint64_t wgcCapacityPressureModeMismatchTotal;
    uint32_t wgcSelectedSourceBacktrackThisWindow;
    uint64_t wgcSelectedSourceBacktrackTotal;
    uint64_t wgcPostStopFrameDropTotal;
    uint32_t wgcPostStopFrameDropMaxUs;
    uint32_t wgcCoverageRepeatHoldCount;
    uint32_t wgcCoverageDelayTicksCurrent;
    double wgcAudioLeadExcessMsCurrent;
    bool wgcCoverageRepeatActiveCurrent;
    bool encoderTooSlowForTargetCurrent;
    bool wgcLowSourceModeActive;
    bool wgcLiveRecoveryModeActive;
    bool wgcReservePressureActive;
    uint64_t wgcLowSourceStateChangeTick;
    uint64_t wgcLiveRecoveryStateChangeTick;
    bool wgcSourceStarvedCurrent;
    bool wgcSchedulerLimitedCurrent;
    bool wgcEncoderRecoveryLimitedCurrent;
    bool wgcActiveDelayRepeatClassKnown;
    ce::capture_policy::WgcActiveDelayWindowClass wgcActiveDelayLastRepeatClass;
    uint64_t wgcActiveDelayLastRepeatClassLogTick;
    int64_t lastEmittedWgcSourceQpc;
    int64_t lastEmittedWgcSelectionQpc;
    int64_t lastEmittedInjectSourceQpc;
    int64_t lastWarmupWgcSourceQpc;
    int64_t wgcStartupBarrierQpc;
    uint32_t wgcStartupBarrierDroppedFrames;
    bool wgcStartupPreLiveDelayComplete;
    uint32_t wgcStartupPreLiveDelayDroppedFrames;
    int64_t wgcAvSyncScheduleOffsetQpc;
    int64_t wgcAvSyncStartupAudioAnchorQpc;
    int64_t wgcAvSyncStartupVideoQpc;
    int64_t wgcAvSyncStartupEffectiveDelayQpc;
    int64_t wgcStartupReserveWaitStartQpc;
    uint32_t wgcStartupReserveWaitCount;
    bool wgcStartupHistoryProtectionLogged;
    int64_t wgcStartupReserveWaitInitialSpanUs;
    uint32_t wgcStartupReserveWaitFreshenedMax;
    uint32_t wgcFreshWarmupFrameCount;
    uint32_t wgcOldestBufferedFrameAgeUs;
    double wgcCoverageRepeatAccumulator;
    WgcStarvedEpisodeSummary wgcStarvedEpisode{};
    CaptureSessionSummary captureSessionSummary{};
    uint64_t minLoggedWgcStarvedEpisodeMs;
    float maxAudioCaptureLatencyMs;
    int64_t avContentDelayQpc;
    bool avContentDelayActive;
    bool wgcSmoothnessFloorConfigured;
    bool wgcSmoothnessDelayDesired;
    size_t injectContentDelayFrames;
    double injectResidualEstimateMs;
    double avContentDelayFrames;
    LARGE_INTEGER cycleStartQpc{};
    uint64_t cycleLiveTicksOutputStart;
    uint32_t outputShortfallTicks;
    bool activeScreenGrab;
    bool useScreenGrab;
    uint32_t outputFps;
    uint32_t catchupTicksThisLoop;
    int64_t selectionGridTick;
    int64_t scheduledSampleQpc;
    uint32_t encoderLateTickCount;
    bool drainingOutstandingLiveTicks;
    int64_t scheduledOutputQpc;
    QueuedFrame frame{};
    bool popped;
    bool wgcTelemetryTickArmed;
    uint32_t wgcBufferedAtTickStart;
    bool wgcFreshAvailableAtTickStart;
    bool wgcReserveAvailableAtTickStart;
    bool wgcSelectionDelayAppliedThisTick;
    bool wgcProactiveOverloadRepeatThisTick;
    bool wgcDelayRealizationRecordedThisTick;
    QueuedFrame* frameToProcess;
    bool isDuplicate;
    bool duplicateFromDeferred;
    bool duplicateFromTimerRebase;
    bool wantsTrueRepeatLastFrame;
    bool hasRepeatLastFramePath;
    size_t injectReserveFrames;
    bool consumesCfrTick;
    bool isDrainPhase;
    bool isLivePhase;
    bool scheduledLiveCfrTick;
    bool lowSourceMode;
    bool deepUnderfeed;
    bool preferUniformActiveDelayCadence;
    ce::capture_policy::WgcAdaptiveTelemetry activeDelayTelemetry{};
    uint32_t wgcSourceJitterAvgUs;
    uint32_t wgcPredictorJitterUs;
    int64_t effectiveSelectionTargetQpc;
    uint32_t activeDelaySoftLateTargetUs;
    int64_t minFreshTimestampQpc;
    int64_t baseStaleFallbackMinTimestampQpc;
    int64_t staleFallbackMinTimestampQpc;
    bool skippedTooNewForSlot;
    bool olderFrameAvoidedRepeatThisTick;
    std::vector<size_t>* candidateIndices;
    bool usingFreshCandidateSet;
    size_t selectedIndex;
    int64_t candidateSelectionTimestamp;
    int64_t candidateRawSelectionTimestamp;
    bool encoderLimitedSmoothnessForBacktrack;
    bool selectedActiveDelayCandidateRelaxed;
    ce::capture_policy::WgcActiveDelayWindowClass selectedActiveDelayWindowClass;
    bool selectedPostStallSafeFrame;
    bool canHoldFreshFrame;
    int64_t kMaxFrameAgeMs;
    QueuedFrame temp{};
    bool inWgcWarmup;
    uint64_t warmupElapsedMs64;

    void ReleaseQueuedFrameTexture(QueuedFrame& queuedFrame);
    void DiscardQueuedFrame(QueuedFrame& queuedFrame);
    void accumulateCaptureSummarySample(bool useScreenGrabSession, uint32_t srcFpsX100Val, uint32_t srcJitterUsVal, uint32_t dupNoSource,
            uint32_t dupDeferred, uint32_t dupTimer, uint32_t dupDrain, uint32_t oldestBufferedFrameAgeUs,
            double shortfallDurationMs, double sustainableOutputFps);
    bool shouldLogWgcStarvedEpisode(uint64_t durationMs, uint64_t outputTicks, uint64_t duplicateTicks,
                                                uint32_t peakFreshMissPermille);
    void finishWgcStarvedEpisode(uint64_t durationMs, uint64_t outputTicks, uint64_t duplicateTicks);
    void ClearBufferedInjectFrames();
    void ClearBufferedWgcFrames();
    void ResetWarmupWgcFreshness(bool resetStartupDiagnostics = true);
    void TrackWarmupWgcFreshFrame(const QueuedFrame& queuedFrame);
    uint32_t updateLiveCfrShortfall(int64_t nowQpc);
    int64_t qpcToUs(int64_t qpcDelta);
    void observeCaptureSyncPhaseSource(const char* path,
                                                    ce::capture_policy::CfrCadencePhaseLockState& state,
                                                    int64_t sourceTimestampQpc);
    int64_t applyCaptureSyncPhaseTarget(const char* path,
                                                 ce::capture_policy::CfrCadencePhaseLockState& state,
                                                 int64_t baseTargetQpc, int64_t sourceReferenceQpc);
    int64_t getWgcRawSelectionTimestamp(const QueuedFrame& frame);
    int64_t getWgcEffectiveContentDelayQpc();
    bool isWgcEffectiveContentDelayActive();
    uint32_t getWgcSmoothnessOutputFps();
    bool shouldUseWgcSmoothnessBaseConfig();
    uint32_t getWgcSmoothnessDesiredFramesForConfig();
    uint32_t getWgcSmoothnessRetainedFramesBudget();
    bool isWgcSmoothnessSourceRateEligibleNow();
    bool shouldAttemptWgcStartupSmoothnessBufferNow();
    int64_t getWgcStartupSmoothnessTargetDelayQpc(bool attempted);
    const char* getWgcSmoothnessBufferReason();
    uint32_t getWgcDelayReservoirLowWaterFramesForDelay(int64_t delayQpc);
    uint32_t getWgcDelayReservoirTargetFramesForDelay(int64_t delayQpc);
    uint32_t getWgcDelayReservoirLowWaterFrames();
    uint32_t getWgcDelayReservoirTargetFrames();
    uint32_t getWgcRetainedFrameCap();
    void updateWgcIngressPressure(const char*);
    uint32_t trimBufferedWgcToRetainedCap(const char* reason);
    uint32_t trimBufferedWgcStartupWaitToRetainedCap(const char* reason);
    uint32_t trimBufferedWgcForPoolPressure(const char* reason);
    void recordWgcDelayResidualSample(int64_t signedResidualUs, uint64_t& samples, uint64_t& absAccumUs, int64_t& signedAccumUs,
            uint32_t& absMaxUs, uint32_t& lateMaxUs, uint32_t& earlyMaxUs, std::array<uint32_t, 256>& histogram,
            uint64_t& windowSamples, uint64_t& windowAbsAccumUs, int64_t& windowSignedAccumUs, uint32_t& windowAbsMaxUs,
            uint32_t& windowLateMaxUs, std::array<uint32_t, 256>& windowHistogram);
    bool recordWgcDelayRealization(int64_t predictedSignedResidualUs, int64_t rawSignedResidualUs);
    uint32_t wgcDelayResidualHistogramP95Us(const std::array<uint32_t, 256>& histogram,
                                                   uint64_t samples);
    uint32_t wgcDelayResidualP95Us();
    uint32_t wgcDelayResidualWindowP95Us();
    uint32_t wgcDelayRawResidualP95Us();
    uint32_t wgcDelayRawResidualWindowP95Us();
    uint32_t loadEncoderOverloadFlags();
    bool isWgcCapacityPressureActive();
    bool isWgcTrueSourceStarvedForCapacityPolicy();
    bool isWgcEncoderLimitedSmoothnessMode();
    size_t pruneStaleWgcVisualDebt(int64_t liveNowQpc, const char* reason, bool allowDropAll,
                                           int64_t immutableSelectionTargetQpc);
    void noteActivePathMismatchDiscard(bool frameIsInjectMode, const char* source);
    void discardActivePathMismatchFrame(QueuedFrame& mismatchedFrame, const char* source, bool queuedFrame);
    int64_t computeWgcSelectionTargetForTick(int64_t scheduledQpcForTick, int64_t selectionGridTickForTick,
                                                          bool applyLiveDelay);
    int64_t computeWgcSelectionTargetQpc(bool applyLiveDelay);
    int64_t computeLiveWgcSelectionTargetQpc();
    int64_t computeDelayedWgcSelectionTargetQpc();
    int64_t clampWgcSelectionTargetQpc(int64_t selectionTargetQpc, int64_t liveNowQpc);
    int64_t computeLiveTimelineElapsedUs(int64_t scheduledQpcForTick);
    bool tryPopBufferedWgcFrameForTarget(int64_t selectionTargetQpc, int64_t liveSelectionTargetQpc,
                                                   int64_t liveNowQpc, bool selectionDelayApplied,
                                                   QueuedFrame* selectedFrame,
                                                   bool* repeatedBecauseNoFrameCoverage = nullptr);
    void inspectBufferedWgcCoverageForTarget(int64_t selectionTargetQpc, bool activeDelaySelection,
                                                       uint32_t requiredReserveFrames, bool* hasFrameForTick,
                                                       bool* hasReserveFrame);
    ce::cursor::CaptureState selectCursorStateForScheduledQpc(int64_t scheduledQpc, const QueuedFrame& referenceFrame,
                                                    const char* outputKind);
    MediaEncoderSession::ScreenGrabPrivacyContext sampleScreenGrabPrivacyContext();
    void observeScreenGrabPrivacyWarmup();
    ce::screen_grab_privacy::GateDecision evaluateScreenGrabPrivacy(const QueuedFrame* freshFrame);
    void requestPrivacyFailClosedStop(const char* reason);
    bool submitPrivacyBlackFrame(const QueuedFrame& referenceFrame, int64_t mediaTimestampQpc,
                                           int64_t scheduledQpc, int64_t timelineElapsedUs);
    bool repeatLastFrameForScheduledQpc(int64_t scheduledQpc);
    bool recoverScheduledFreshEncodeFailure(bool scheduledCfrTick, bool freshEncodeSucceeded,
                                                      bool freshEncodeDeferred, int64_t scheduledQpc,
                                                      const QueuedFrame* failedFrame, const char* context);
    void releaseWgcLeaseAfterMediaEngineCopy(QueuedFrame& encodedFrame, const char* context);
    void recordDuplicate(const QueuedFrame* duplicateFrame, const InjectFrameLineage* duplicateLineage,
                                   bool duplicateFromDrainReason, bool duplicateFromDeferredReason,
                                   bool duplicateFromTimerRebaseReason, bool duplicateFromCatchupReason = false,
                                   bool duplicateFromCapacityPacerReason = false);
    void advanceWakeDeadlineForCatchupTick();
    void emitCatchupRepeats(const InjectFrameLineage* duplicateLineage);
    uint32_t activeDelayRepeatClusterTicks();
    uint32_t currentDelayResidualAvgAbsUs();
    uint32_t currentDelayResidualP95Us();
    uint32_t currentDelayResidualLateMaxUs();
    uint32_t currentRawDelayResidualAvgAbsUs();
    uint32_t currentRawDelayResidualP95Us();
    uint32_t currentRawDelayResidualLateMaxUs();
    uint32_t currentCombinedDelayResidualAvgAbsUs();
    uint32_t currentCombinedDelayResidualP95Us();
    uint32_t currentCombinedDelayResidualLateMaxUs();
    ce::capture_policy::WgcActiveDelayWindowClass activeDelayWindowClassFor(bool hardSafeCandidateAvailable);
    bool rawActiveDelayCandidateSafe(int64_t rawSelectionTimestamp);
    uint32_t activeDelayCandidateLateResidualUs(const QueuedFrame& candidate);
    bool isActiveDelayCandidateHardSafe(const QueuedFrame& candidate);
    bool isActiveDelayCandidateSoftSafe(const QueuedFrame& candidate);
    bool hasActiveDelayHardSafeCandidate();
    bool hasActiveDelaySoftSafeCandidate();
    uint32_t currentOldestSoftSafeAgeUs();
    uint32_t currentRepeatReserveSpanUs();
    void recordActiveDelayRepeatClass(ce::capture_policy::WgcActiveDelayWindowClass repeatWindowClass, bool hardSafeCandidateAvailable,
                    bool softSafeCandidateAvailable);
    bool isCurrentSyncDelayHoldSourceLimited(bool softSafeCandidateAvailable);
    void recordActiveDelayRepeatLowerBound(bool softSafeCandidateAvailable,
                                                               bool syncDelayHoldSourceLimited);
    void recordSyncDelayRepeatHold(bool countRepeatClusterPressure, bool hardSafeCandidateAvailable,
                                                       bool softSafeCandidateAvailable);
    void buildCandidateList(std::vector<size_t>* outIndices, bool requireFresh,
                                          bool allowRelaxedActiveDelayResidual);
    int64_t bestCandidateDistance(const std::vector<size_t>& indices);
    bool finalSelectionWithinActiveDelayHardLimit(size_t candidateIndex);
    uint32_t activeDelayLateResidualUsForIndex(size_t candidateIndex);

    bool Init();
    void InitState();
    void LoopStart();
    void LoopPressure();
    void LoopCatchup();
    void LoopWgcTarget();
    void LoopWgcSelect();
    void LoopStartup();
    void LoopEmit();
    void LoopEncode();
    void LoopHealth();
    void Shutdown();
    void SelectWgcFrameCapture();
    void SelectWgcFrameUniformPath();
    void SelectWgcFrameUniform();
    void SelectWgcFrameUniformTail();
    void SelectWgcFrameUniformVfr();
    void SelectInjectFrame();
    void RefreshInjectFinalOutputDisplayTiming(size_t firstNewBufferedFrame);
    void CommitWarmupSync();
    void CommitWarmupReset();
    // tryPopBufferedWgcFrameForTarget selection chunks (parameterless; they read the
    // active-call parameter members above).
    bool TryPopWgcSelectionCore();
    bool TryPopWgcSelectionFinalize();
};
