// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once
#include <cstdint>

static const uint32_t g_SharpenCasFragmentShaderSpv[] = {
#include "sharpencasfragmentshaderspv_part1.inl"
#include "sharpencasfragmentshaderspv_part2.inl"
};
