// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once
#include <cstdint>

static const uint32_t g_SharpenRcasComputeShaderSpv[] = {
#include "sharpenrcascomputeshaderspv_part1.inl"
#include "sharpenrcascomputeshaderspv_part2.inl"
};
