// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once
#include <cstdint>

static const uint32_t g_SharpenCasComputeShaderSpv[] = {
#include "sharpencascomputeshaderspv_part1.inl"
#include "sharpencascomputeshaderspv_part2.inl"
};
