"""Compile, validate, and embed the CAS/RCAS sharpen shaders.

Emits DXBC for the D3D10/11/12 renderers and SPIR-V for the Vulkan layer from
the two shader trees, both compiled against the vendored AMD headers in
``external/fidelityfx``.

The D3D path resolves ``#include`` by inlining, because ``D3DCompile`` is called
here without an ``ID3DInclude`` implementation. Inlining is textual and keeps
every directive in place, so the compiler still sees the headers' own include
guards and nothing is deduplicated behind its back.

Run it after changing any sharpen shader or after re-vendoring the headers; the
generated headers are committed like the overlay's.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from compile_shaders import compile_shader, format_array

ROOT = Path(__file__).resolve().parents[1]
HLSL_DIR = ROOT / "hook" / "shaders"
GLSL_DIR = ROOT / "hook" / "vulkan_layer" / "shaders"
FFX_INCLUDE_DIR = ROOT / "external" / "fidelityfx" / "gpu"
COMMON_DIR = ROOT / "hook" / "common"
DXBC_PART_DIR = COMMON_DIR / "sharpen_shader_bytecode"
DXBC_HEADER = COMMON_DIR / "sharpen_shader_bytecode.h"
SPIRV_HEADER = COMMON_DIR / "sharpen_shader_spirv.h"
TOOL_DIR = ROOT / "build" / "msys64" / "clang64" / "bin"

# Shader model 5.0 only. The FidelityFX HLSL backend uses SM5 bit and packing
# intrinsics in helpers that a 4.0 profile has to reject even when the sharpen
# entry points never reach them, and every device that can run this pass at all
# supports SM5.
DXBC_SHADERS = (
    ("sharpen_fullscreen.hlsl", "vs_5_0", "g_SharpenVS_5_0"),
    ("sharpen_cas.hlsl", "ps_5_0", "g_SharpenPS_Cas_5_0"),
    ("sharpen_rcas.hlsl", "ps_5_0", "g_SharpenPS_Rcas_5_0"),
)

SPIRV_SHADERS = (
    ("sharpen_fullscreen.vert", "vert", "g_SharpenVertexShaderSpv"),
    ("sharpen_cas.frag", "frag", "g_SharpenCasFragmentShaderSpv"),
    ("sharpen_rcas.frag", "frag", "g_SharpenRcasFragmentShaderSpv"),
)

BANNER = (
    "// Auto-generated shader bytecode - do not edit manually",
    "// Generated by tools/compile_sharpen_shaders.py",
    "",
)

INCLUDE_PATTERN = re.compile(rb'^\s*#include\s+"([^"]+)"\s*$')


def inline_includes(path: Path, seen: list[Path] | None = None) -> bytes:
    """Textually expand quoted includes, resolved relative to the including file.

    Cycles are a hard error rather than a truncation: a silently dropped include
    would compile into a shader missing half its algorithm.
    """
    seen = list(seen or [])
    if path in seen:
        chain = " -> ".join(str(entry) for entry in seen + [path])
        raise RuntimeError(f"Cyclic shader include: {chain}")
    seen.append(path)

    out: list[bytes] = []
    for line in path.read_bytes().splitlines(keepends=True):
        match = INCLUDE_PATTERN.match(line.rstrip(b"\r\n"))
        if not match:
            out.append(line)
            continue
        included = (path.parent / match.group(1).decode("utf-8")).resolve()
        if not included.is_file():
            raise RuntimeError(f"{path}: cannot resolve #include \"{match.group(1).decode('utf-8')}\"")
        out.append(b"// --- begin " + str(included).encode("utf-8") + b" ---\n")
        out.append(inline_includes(included, seen))
        out.append(b"\n// --- end " + str(included).encode("utf-8") + b" ---\n")
    return b"".join(out)


def build_dxbc() -> list[str]:
    DXBC_PART_DIR.mkdir(parents=True, exist_ok=True)
    part_files: list[str] = []
    for source_name, target, symbol in DXBC_SHADERS:
        source = inline_includes(HLSL_DIR / source_name)
        data = compile_shader(source, target, symbol)
        part_file = symbol[2:].lower() + ".h"
        part_files.append(part_file)
        part = list(BANNER) + ["#pragma once", "#include <cstdint>", "", format_array(symbol, data)]
        (DXBC_PART_DIR / part_file).write_text("\n".join(part).rstrip("\n") + "\n", encoding="utf-8", newline="\n")

    umbrella = list(BANNER) + ["#pragma once", ""]
    umbrella += [f'#include "sharpen_shader_bytecode/{part_file}"' for part_file in part_files]
    DXBC_HEADER.write_text("\n".join(umbrella).rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    return part_files


def emit_spirv_array(symbol: str, payload: bytes) -> str:
    if not payload or len(payload) % 4:
        raise RuntimeError(f"Invalid SPIR-V payload for {symbol}")
    words = [int.from_bytes(payload[offset : offset + 4], "little") for offset in range(0, len(payload), 4)]
    lines = [f"static const uint32_t {symbol}[] = {{"]
    for offset in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08x}u" for word in words[offset : offset + 8]) + ",")
    lines.append("};")
    return "\n".join(lines)


def build_spirv() -> None:
    compiler = TOOL_DIR / "glslangValidator.exe"
    optimizer = TOOL_DIR / "spirv-opt.exe"
    validator = TOOL_DIR / "spirv-val.exe"
    if not compiler.is_file() or not optimizer.is_file() or not validator.is_file():
        raise RuntimeError("Bundled glslangValidator.exe, spirv-opt.exe and spirv-val.exe are required")

    arrays: list[str] = []
    for source_name, stage, symbol in SPIRV_SHADERS:
        source = GLSL_DIR / source_name
        output = GLSL_DIR / f"{source_name}.spv"
        subprocess.run(
            [
                str(compiler),
                "-V",
                "--target-env",
                "vulkan1.2",
                "-I" + str(FFX_INCLUDE_DIR),
                "-I" + str(GLSL_DIR),
                "-S",
                stage,
                str(source),
                "-o",
                str(output),
            ],
            check=True,
        )
        # The FidelityFX GLSL headers define far more than any one entry point
        # uses, and glslang emits all of it with full debug information: the
        # unoptimized CAS fragment shader is 61 KB. Optimizing and stripping
        # takes it to about 6 KB, which is both a tenth of the binary to embed
        # and a tenth of the work the driver does compiling it at pipeline
        # creation. Validation runs on the module that actually ships.
        subprocess.run([str(optimizer), "-O", "--strip-debug", str(output), "-o", str(output)], check=True)
        subprocess.run([str(validator), "--target-env", "vulkan1.2", str(output)], check=True)
        arrays.append(emit_spirv_array(symbol, output.read_bytes()))

    SPIRV_HEADER.write_text(
        "\n".join(BANNER) + "\n#pragma once\n\n#include <cstdint>\n\n" + "\n\n".join(arrays) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    print("Compiling sharpen shaders (DXBC)...", file=sys.stderr)
    parts = build_dxbc()
    print(f"Written {DXBC_HEADER} and {len(parts)} shader header(s)", file=sys.stderr)
    print("Compiling sharpen shaders (SPIR-V)...", file=sys.stderr)
    build_spirv()
    print(f"Written {SPIRV_HEADER}", file=sys.stderr)


if __name__ == "__main__":
    main()
