"""Compile, validate, and embed the Vulkan overlay shaders."""

from __future__ import annotations

import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHADER_DIR = ROOT / "hook" / "vulkan_layer" / "shaders"
OUTPUT_HEADER = ROOT / "hook" / "common" / "overlay_shader_spirv.h"
TOOL_DIR = ROOT / "build" / "msys64" / "clang64" / "bin"

SHADERS = (
    ("overlay.vert", "vert", "g_VertexShaderSpv"),
    ("overlay_textured.frag", "frag", "g_FragmentShaderSpv"),
    ("overlay_solid.frag", "frag", "g_FragmentShaderSolidSpv"),
    ("overlay_composite.comp", "comp", "g_ComputeCompositeShaderSpv"),
)


def emit_array(symbol: str, payload: bytes) -> str:
    if not payload or len(payload) % 4:
        raise RuntimeError(f"Invalid SPIR-V payload for {symbol}")
    words = [int.from_bytes(payload[offset : offset + 4], "little") for offset in range(0, len(payload), 4)]
    lines = [f"static const uint32_t {symbol}[] = {{"]
    for offset in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08x}u" for word in words[offset : offset + 8]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    compiler = TOOL_DIR / "glslangValidator.exe"
    validator = TOOL_DIR / "spirv-val.exe"
    if not compiler.is_file() or not validator.is_file():
        raise RuntimeError("Bundled glslangValidator.exe and spirv-val.exe are required")

    arrays: list[str] = []
    for source_name, stage, symbol in SHADERS:
        source = SHADER_DIR / source_name
        output = SHADER_DIR / f"{source_name}.spv"
        subprocess.run(
            [str(compiler), "-V", "--target-env", "vulkan1.2", "-S", stage, str(source), "-o", str(output)],
            check=True,
        )
        subprocess.run([str(validator), "--target-env", "vulkan1.2", str(output)], check=True)
        arrays.append(emit_array(symbol, output.read_bytes()))

    OUTPUT_HEADER.write_text(
        "// Generated by tools/compile_vulkan_overlay_shaders.py. Do not edit.\n"
        "#pragma once\n\n#include <cstdint>\n\n"
        + "\n\n".join(arrays)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Written {OUTPUT_HEADER}")


if __name__ == "__main__":
    main()
