// Auto-generated shader bytecode - do not edit manually
// Generated by tools/compile_sharpen_shaders.py

#pragma once

#include "hook/sharpen/sharpen_shader_spirv/sharpenvertexshaderspv.h"
#include "hook/sharpen/sharpen_shader_spirv/sharpencasfragmentshaderspv.h"
#include "hook/sharpen/sharpen_shader_spirv/sharpenrcasfragmentshaderspv.h"
#include "hook/sharpen/sharpen_shader_spirv/sharpencascomputeshaderspv.h"
#include "hook/sharpen/sharpen_shader_spirv/sharpenrcascomputeshaderspv.h"
